{"name": "test_001", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './temp/temp_pic.png'", "trace": "self = <TestCase.test_admin.TestAdmin object at 0x101eb59a0>\ndrivers = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1c25be16f83aa5c63235d7ca7e6c3b18\")>\n\n    @allure.story('管理员登录用例')\n    def test_001(self, drivers):\n        login = Admin(drivers)\n        with allure.step('打开DMSP'):\n            login.get_url(ini.url)\n            login.click_pass_button()\n        with allure.step('输入账号、密码、验证码'):\n            login.input_username(ini.username)\n            login.input_password(ini.password)\n            login.input_verify_code(ini.verify_code)\n        with allure.step('点击登录'):\n            login.click_login_button()\n        with allure.step('判断是否登录成功'):\n            result = login.get_url_now()\n            log.info(result)\n            assert 'list' in result\n>           save_pic(drivers)\n\ntest_admin.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../utils/picture_save.py:7: in save_pic\n    allure.attach.file(\"./temp/temp_pic.png\", attachment_type=allure.attachment_type.PNG)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py:203: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_pytest/listener.py:256: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/reporter.py:160: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/logger.py:39: in report_attached_file\n    shutil.copy2(source, destination)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py:475: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = './temp/temp_pic.png'\ndst = PosixPath('/Users/a1234/dsmp-selenium+pytest+allure/TestCase/report/result/133054ba-96c3-4b66-b117-b1beac5d12f5-attachment.png')\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: './temp/temp_pic.png'\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py:260: FileNotFoundError"}, "steps": [{"name": "打开DMSP", "status": "passed", "start": 1722925286863, "stop": 1722925289851}, {"name": "输入账号、密码、验证码", "status": "passed", "start": 1722925289851, "stop": 1722925291742}, {"name": "点击登录", "status": "passed", "start": 1722925291742, "stop": 1722925292836}, {"name": "判断是否登录成功", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './temp/temp_pic.png'\n", "trace": "  File \"/Users/a1234/dsmp-selenium+pytest+allure/TestCase/test_admin.py\", line 41, in test_001\n    save_pic(drivers)\n  File \"/Users/a1234/dsmp-selenium+pytest+allure/utils/picture_save.py\", line 7, in save_pic\n    allure.attach.file(\"./temp/temp_pic.png\", attachment_type=allure.attachment_type.PNG)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py\", line 203, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_pytest/listener.py\", line 256, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/reporter.py\", line 160, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    raise exception.with_traceback(exception.__traceback__)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/logger.py\", line 39, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py\", line 475, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py\", line 260, in copyfile\n    with open(src, 'rb') as fsrc:\n         ^^^^^^^^^^^^^^^\n"}, "attachments": [{"source": "133054ba-96c3-4b66-b117-b1beac5d12f5-attachment.png", "type": "image/png"}], "start": 1722925292836, "stop": 1722925293152}], "attachments": [{"name": "log", "source": "8d077147-5cb6-4518-a2b7-36ff2f05be09-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0784b07b-c1b5-4fc4-833a-77435dbe49eb-attachment.txt", "type": "text/plain"}], "start": 1722925286863, "stop": 1722925293158, "uuid": "1ab252a3-4446-49e7-b202-b13366698d6d", "historyId": "26161d08421f3bc6b73cea28e51fb9e1", "testCaseId": "26161d08421f3bc6b73cea28e51fb9e1", "fullName": "TestCase.test_admin.TestAdmin#test_001", "labels": [{"name": "story", "value": "管理员登录用例"}, {"name": "feature", "value": "测试超管功能"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_admin"}, {"name": "subSuite", "value": "TestAdmin"}, {"name": "host", "value": "1234s-MacBook-Air.local"}, {"name": "thread", "value": "94539-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_admin"}]}